fieldLayouts:
  41d838ff-7ed0-4870-b115-ab43a248dc8a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 205260e8-8ea2-4df3-a625-0b806fd775de
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9dcb8429-a20d-4150-adaa-aea9d1559c21
        userCondition: null
fs: fifthcard
handle: fifthcard
name: fifthcard
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
