fieldLayouts:
  2fc09ff8-da20-4ce1-bda5-a9034f5e7cea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ccfd4e97-5145-4bca-b6bb-536726247b2c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7ce21289-d3c9-451b-a6f1-d6c010eb3807
        userCondition: null
fs: firstcard
handle: firstcard
name: firstcard
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
