fieldLayouts:
  11612677-ffa5-41ab-a15a-24e499f91f53:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: fcf3a72d-5533-426f-b02d-d438096174d3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d3b3277d-f92b-4bbf-995b-cdd96a117109
        userCondition: null
fs: thirdcard
handle: thirdcard
name: thirdcard
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
