defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  4586431e-47b3-4e53-b41c-a743354a2d7e: # pulkit
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
